# Use the official PostgreSQL image as a base
FROM postgres:latest

# Expose the default PostgreSQL port
EXPOSE 5432

# Set environment variables
ENV POSTGRES_DB=dh2p_database
ENV POSTGRES_USER=mbsuperadmin
ENV POSTGRES_PASSWORD=NeClownLast44*404*#Hahaha24-LS
