- name: Deploy and manage e-shop virtualization project
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Start pgAdmin container
      community.docker.docker_container:
        name: pgadmin
        image: dpage/pgadmin4
        env:
          PGADMIN_DEFAULT_EMAIL: admin@example.com
          PGADMIN_DEFAULT_PASSWORD: admin
        ports:
          - "5050:80"
        networks_cli_compatible: yes
        networks:
          - name: e-shop-virtualization_net1
        state: started
        restart_policy: unless-stopped
      when: pgadmin_enabled|bool

    - name: Stop pgAdmin container
      community.docker.docker_container:
        name: pgadmin
        state: absent
      when: not pgadmin_enabled|bool
